### ISSUE TITLE
在调用performClick出现异常

### ISSUE THREAD

**Issue by w513209188** [AlexMofer/GradientTabStrip#1]
在调用performClick（）方法火出现内存泄漏 问题，具体分析是由于 if (clickListener != null && notifyListener) {
                clickListener.onItemClick(mPosition);
            }
这个监听引起的，  顺便问下 这里应该是不需要再次监听onItemClick了吧  不然会造成 死循环  最终导致卡死
  具体的详细代码 请作者查看！

**Comment by AlexMofer** [comment]
你是在外部调用performClick(int position)方法？其实这个方法内部实现是调用了performClick(int position, boolean smoothScroll, boolean notifyListener)方法，即performClick(position, false, true)，参数notifyListener仅仅是决定是否通知监听器，这个监听器是外部监听，不会造成死循环，除非你在点击事件的监听里面又调用performClick(int position)方法才会出现死循环，View本身的performClick()方法也是会通知外部监听器的，这里因此保持一致：
```java
public boolean performClick() {
        final boolean result;
        final ListenerInfo li = mListenerInfo;
        if (li != null && li.mOnClickListener != null) {
            playSoundEffect(SoundEffectConstants.CLICK);
            li.mOnClickListener.onClick(this);
            result = true;
        } else {
            result = false;
        }

        sendAccessibilityEvent(AccessibilityEvent.TYPE_VIEW_CLICKED);
        return result;
    }
```
performClick(int position, boolean smoothScroll, boolean notifyListener)方法在控件内部会多次调用，clickListener的持有在View被销毁时也会同时释放，因此不会导致内存泄漏，可能你要再找找是不是其他问题导致的。
