### ISSUE TITLE
大神,这个项目能不能用在eclipse工程4.4-API-1.9里面

### ISSUE THREAD

**Issue by MorningSongTeacher** [AlexMofer/GradientTabStrip#3]
大神,使用这个项目时, 如果使用双手快速按底部的按钮, 第三个tab发现按钮会被默认选上, 需要再次点击一次才能取消, 这个项目能不能用在eclipse工程4.4-API-1.9里面,需要注意些什么,我没试成功, 创建的类会报出The hierarchy of the type GradientTabStripAdapter is inconsistent

**Comment by AlexMofer** [comment]
感谢反馈，快速点击确实会出现你描述的错误，但并不一定是第三个，每个位置都可能出现。那是点按后Drawable的状态刷新错误导致的。之后会修复该问题。

目前这个版本估计没法用到Eclipse上，因为使用了com.android.support:support-core-ui:25.3.1，貌似官方已经不提供这些新版支持库的Eclipse版本。

如果你能解决包的问题，那就可以用。

这个项目是基于[BaseTabStrip](https://github.com/AlexMofer/BaseTabStrip)项目的，而这个项目需要v4支持库经过拆分了的support-core-ui支持库，当然你也可以使用整个的v4支持库来替代。但需要注意其版本，若使用v24.0.0以下的，那么你可能需要修改代码，因为有些使用到的方法在v24.0.0以上已经被修改了。

最后，Drawable状态的错误问题将在支持库的下一个release版本出来时一并修改，非常感谢。

**Comment by AlexMofer** [comment]
Fix by v25.4.0
